name: health_care_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # localization
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0

  # location
  location: ^7.0.0
  latlong2: ^0.9.1
  flutter_map: ^8.1.1

  # widgets
  file_picker: ^9.2.0
  flutter_svg: ^2.0.17
  motion_toast: ^2.12.1
  mesh_gradient: ^1.3.8
  table_calendar: ^3.1.3
  dropdown_button2: ^2.3.9
  flutter_slidable: ^4.0.0
  flutter_speed_dial: ^7.0.0
  animated_toggle_switch: ^0.8.4
  syncfusion_flutter_pdf: ^28.2.11
  material_design_icons_flutter: ^7.0.7296
  flutter_staggered_grid_view: ^0.7.0

  # http
  http: ^1.3.0
  # universal_html: ^2.2.4
  path_provider: ^2.1.5
  path: ^1.9.1

  # url
  url_launcher: ^6.3.1

  # permission
  permission_handler: ^11.4.0

  # firebase
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

  # mobile
  flutter_native_splash: ^2.4.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # mobile
  flutter_launcher_icons: ^0.14.3

  # tests
  build_runner: ^2.4.15
  mockito: ^5.4.5
  firebase_auth_mocks: ^0.14.1
  firebase_core_platform_interface: ^5.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#515b92"
  image: "assets/splash.png"
  android: true
  ios: true
  web: false

  android_12:
    color: "#515b92"
    image: "assets/splash.png"

flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/photos/
