name: health_care_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # localization
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0

  # location
  location: ^7.0.0
  latlong2: ^0.9.1
  flutter_map: ^8.1.1

  # widgets
  file_picker: ^9.2.0
  flutter_svg: ^2.0.17
  motion_toast: ^2.12.1
  mesh_gradient: ^1.3.8
  table_calendar: ^3.1.3
  dropdown_button2: ^2.3.9
  flutter_slidable: ^4.0.0
  flutter_speed_dial: ^7.0.0
  animated_toggle_switch: ^0.8.4
  syncfusion_flutter_pdf: ^28.2.11
  material_design_icons_flutter: ^7.0.7296
  flutter_staggered_grid_view: ^0.7.0

  # http
  http: ^1.3.0
  universal_html: ^2.2.4
  path_provider: ^2.1.5
  path: ^1.9.1

  # url
  url_launcher: ^6.3.1

  # permission
  permission_handler: ^11.4.0

  # firebase
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

  # mobile
  flutter_native_splash: ^2.4.5

  # test
  benchmark_harness: ^2.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # mobile
  flutter_launcher_icons: ^0.14.3

  # tests
  build_runner: ^2.4.15
  mockito: ^5.4.5
  firebase_auth_mocks: ^0.14.1
  test_cov_console: ^0.2.2
  golden_toolkit: ^0.15.0
  firebase_core_platform_interface: ^5.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#515b92"
  image: "assets/splash.png"
  android: true
  ios: true
  web: false

  android_12:
    color: "#515b92"
    image: "assets/splash.png"

flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/photos/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
