name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-vm:
    name: Run Flutter tests on VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter tests on VM
        run: flutter test --dart-define=BENCHMARK_REPEAT=10

      - uses: actions/upload-artifact@v3
        with:
          name: benchmark-report-vm
          path: global_benchmark_report_*.json

  test-web:
    name: Run Flutter tests on Web (Chrome)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter tests on Web
        run: flutter test --platform chrome --dart-define=BENCHMARK_REPEAT=10

      - uses: actions/upload-artifact@v3
        with:
          name: benchmark-report-web
          path: global_benchmark_report_*.json

  collect-artifacts:
    name: Collect Benchmark Reports
    runs-on: ubuntu-latest
    needs: [test-vm, test-web]
    steps:
      - name: Download VM Benchmark Report
        uses: actions/download-artifact@v3
        with:
          name: benchmark-report-vm
          path: artifacts/vm

      - name: Download Web Benchmark Report
        uses: actions/download-artifact@v3
        with:
          name: benchmark-report-web
          path: artifacts/web

      - name: List Downloaded Files
        run: ls -R artifacts
