name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test-vm:
    name: Run Flutter tests on VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter tests on VM
        run: flutter test --dart-define=BENCHMARK_REPEAT=10

      - name: Move Benchmark Report
        run: |
          mkdir -p files
          mv global_benchmark_report_*.json files/

      - name: Commit and Push Benchmark Report
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add files/
          git commit -m "Add VM benchmark report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-web:
    name: Run Flutter tests on Web (Chrome)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter tests on Web and capture output
        run: |
          mkdir -p files
          flutter test --platform chrome --dart-define=BENCHMARK_REPEAT=10 > test_output.log

      - name: Extract benchmark report from log
        run: |
          awk '/BENCHMARK_REPORT_START/,/BENCHMARK_REPORT_END/' test_output.log | sed '1d;$d' > files/web_benchmark_report.json
          echo "Extracted Web Report:"
          cat files/web_benchmark_report.json

      - name: Commit and Push Web Benchmark Report
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add files/web_benchmark_report.json
          git commit -m "Add Web benchmark report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
