# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 test-vm:
    name: Run Flutter tests on VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use the Flutter action to set up a stable Flutter version.
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install Dependencies
        run: flutter pub get

      # Run tests on the Dart VM (mobile/desktop) and pass the BENCHMARK_REPEAT flag.
      - name: Run Flutter tests on VM
        run: flutter test --dart-define=BENCHMARK_REPEAT=10

      # Upload all benchmark JSON files as an artifact.
      - uses: actions/upload-artifact@v2
        with:
          name: benchmark-report-vm
          path: global_benchmark_report_*.json

  test-web:
    name: Run Flutter tests on Web (Chrome)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install Dependencies
        run: flutter pub get

      # Run tests on the web platform; note the use of --platform chrome.
      - name: Run Flutter tests on Web
        run: flutter test --platform chrome --dart-define=BENCHMARK_REPEAT=10

      - uses: actions/upload-artifact@v2
        with:
          name: benchmark-report-web
          path: global_benchmark_report_*.json
