name: Flutter unit tests (mobile + web)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unit:
    strategy:
      matrix:
        target: [mobile, web]    
    runs-on: ubuntu-latest
    env:
      BENCHMARK_REPEAT: 10 

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: stable
        id: flutter

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ steps.flutter.outputs.cache-path }}
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}

      - name: Enable web & Chrome device
        if: matrix.target == 'web'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y chromium-browser
          flutter config --enable-web
          flutter devices

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests and capture output
        run: |
          mkdir -p perf
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

          if [[ "${{ matrix.target }}" == "web" ]]; then
            flutter test --platform chrome test/unit_test.dart > test_output.log
          else
            flutter test test/unit_test.dart > test_output.log
          fi

          awk '/PERF_REPORT_START/,/PERF_REPORT_END/' test_output.log \
            | sed '1d;$d' \
            > perf/benchmark_${{ matrix.target }}_${TIMESTAMP}.json

      - name: Upload benchmark artefact
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-${{ matrix.target }}-${{ env.TIMESTAMP }}
          path: perf/benchmark_${{ matrix.target }}_${TIMESTAMP}.json
