name: Flutter unit tests (mobile + web)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unit:
    strategy:
      matrix:
        target: [mobile, web]
    runs-on: ubuntu-latest
    env:
      BENCHMARK_REPEAT: 10

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: stable
        id: flutter

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ steps.flutter.outputs.cache-path }}
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}

      - name: Enable web & install Chrome
        if: matrix.target == 'web'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y chromium-browser
          flutter config --enable-web
          flutter devices

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests and capture output
        id: run_tests
        run: |
          set -eo pipefail
          mkdir -p perf

          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

          # choose command per target
          if [[ "${{ matrix.target }}" == "web" ]]; then
            CMD="flutter test --platform chrome"   # add path if you have a single file
          else
            CMD="flutter test"                     # add path if you have a single file
          fi

          # run tests, tee output so it’s both printed and captured
          set +e
          $CMD | tee test_output.log
          EXIT_CODE=${PIPESTATUS[0]}
          set -e

          # always attempt to extract the JSON
          awk '/PERF_REPORT_START/,/PERF_REPORT_END/' test_output.log \
            | sed '1d;$d' \
            > perf/benchmark_${{ matrix.target }}_${TIMESTAMP}.json || true

          # if the tests failed, print the log for easier debugging
          if [[ $EXIT_CODE -ne 0 ]]; then
            echo "===== flutter test FAILED (exit $EXIT_CODE) ====="
            cat test_output.log
          fi

          exit $EXIT_CODE   # propagate success/failure to the job outcome

      - name: Upload benchmark artefact
        if: always()         # upload even if tests failed
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-${{ matrix.target }}-${{ env.TIMESTAMP }}
          path: perf/benchmark_${{ matrix.target }}_${{ env.TIMESTAMP }}.json
          if-no-files-found: warn
