  golden:
    needs: widget
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: mobile
            platformFlag: ''
          - target: web
            platformFlag: '--platform chrome'
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      # Only for web: install Chrome & enable
      - name: Enable web & install Chrome
        if: matrix.target == 'web'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y chromium-browser || true
          flutter config --enable-web

      - name: Run only golden tests on ${{ matrix.target }}
        id: golden_run
        run: |
          set -eo pipefail
          flutter test ${{ matrix.platformFlag }} \
            --tags golden \
            test/widget_tests/golden_tests.dart
        continue-on-error: true

      - name: Upload golden diffs if any
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: golden-diffs-${{ matrix.target }}
          path: |
            **/*.new.png
            **/*.diff.png
